#!/usr/bin/env bash
# build.sh — produce a single-file dist/ctrl for distribution via GitHub Releases
set -euo pipefail

CTRL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${CTRL_DIR}/dist"
OUT="${OUT_DIR}/ctrl"
VERSION="$(cat "${CTRL_DIR}/VERSION" 2>/dev/null || echo "unknown")"

LIBS=(core services deploy remote health audit ext gitlab templates init check info mcp)

mkdir -p "${OUT_DIR}"

{
  echo "#!/usr/bin/env bash"
  echo "# ctrl v${VERSION} — auto-generated by build.sh, do not edit"
  echo "set -euo pipefail"
  echo ""
  echo "CTRL_VERSION=\"${VERSION}\""
  echo ""

  for lib in "${LIBS[@]}"; do
    echo "# ════════════════════════════════════════════════════════════════════════════"
    echo "# lib/${lib}.sh"
    echo "# ════════════════════════════════════════════════════════════════════════════"
    # strip: shebang, set -euo pipefail, CTRL_VERSION= (already set above)
    grep -v '^#!/\|^set -euo pipefail\|^CTRL_VERSION=' "${CTRL_DIR}/lib/${lib}.sh"
    echo ""
  done

  echo "# ════════════════════════════════════════════════════════════════════════════"
  echo "# ctrl.sh — command dispatcher"
  echo "# ════════════════════════════════════════════════════════════════════════════"
  # strip: shebang, set -euo pipefail, CTRL_SELF_DIR block, CTRL_VERSION=, source lines
  grep -v '^#!/\|^set -euo pipefail\|^CTRL_SELF_DIR=\|^CTRL_VERSION=\|^source ' "${CTRL_DIR}/ctrl.sh"

} > "${OUT}"

chmod +x "${OUT}"
echo "Built → ${OUT}"
wc -l "${OUT}" | awk '{print $1 " lines"}'
