#!/usr/bin/env bash
# bundle.sh — concatenate ctrl.sh + lib/*.sh into a single distributable ctrl-bundle.sh
set -euo pipefail

CTRL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${CTRL_DIR}/ctrl-bundle.sh"
LIBS=(core services deploy remote health audit ext)

{
  echo "#!/usr/bin/env bash"
  echo "# ctrl-bundle.sh — auto-generated by bundle.sh, do not edit"
  echo "set -euo pipefail"
  echo ""
  echo "CTRL_SELF_DIR=\"\$(cd \"\$(dirname \"\$(readlink -f \"\${BASH_SOURCE[0]}\")\")\" && pwd)\""
  echo "CTRL_VERSION=\"\$(cat \"\${CTRL_SELF_DIR}/VERSION\" 2>/dev/null || echo unknown)\""
  echo ""

  for lib in "${LIBS[@]}"; do
    echo "# ════════════════════════════════════════════════════════════════════════════"
    echo "# lib/${lib}.sh"
    echo "# ════════════════════════════════════════════════════════════════════════════"
    # strip shebang, set -euo pipefail, and CTRL_VERSION lines already set above
    grep -v '^#!/\|^set -euo pipefail\|^CTRL_VERSION=' "${CTRL_DIR}/lib/${lib}.sh"
    echo ""
  done

  echo "# ════════════════════════════════════════════════════════════════════════════"
  echo "# ctrl.sh — entry point"
  echo "# ════════════════════════════════════════════════════════════════════════════"
  # strip shebang, set -euo pipefail, CTRL_SELF_DIR, CTRL_VERSION, and all source lines
  grep -v '^#!/\|^set -euo pipefail\|^CTRL_SELF_DIR=\|^CTRL_VERSION=\|^source ' "${CTRL_DIR}/ctrl.sh"

} > "${OUT}"

chmod +x "${OUT}"
echo "Bundled → ${OUT}"
wc -l "${OUT}"
