#!/usr/bin/env bash
# ctrl-bundle.sh — auto-generated by bundle.sh, do not edit
set -euo pipefail

CTRL_SELF_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
CTRL_VERSION="$(cat "${CTRL_SELF_DIR}/VERSION" 2>/dev/null || echo unknown)"

# ════════════════════════════════════════════════════════════════════════════
# lib/core.sh
# ════════════════════════════════════════════════════════════════════════════
# core.sh — config loading, logging, OS detection, utility helpers

CTRL_JOURNAL_DIR="${HOME}/.local/share/ctrl"
CTRL_JOURNAL="${CTRL_JOURNAL_DIR}/journal.jsonl"
CTRL_DRY_RUN="${CTRL_DRY_RUN:-0}"
CTRL_VERBOSE="${CTRL_VERBOSE:-0}"

# ── colour ────────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'
  RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'
  RESET=$'\033[0m'
else
  BOLD=''; DIM=''; RED=''; GREEN=''; YELLOW=''; BLUE=''; RESET=''
fi

# ── logging ───────────────────────────────────────────────────────────────────
msg()       { echo "${BLUE}${BOLD}==>${RESET} $*"; }
msg_ok()    { echo "${GREEN}${BOLD}ok${RESET} $*"; }
msg_warn()  { echo "${YELLOW}${BOLD}warn${RESET} $*" >&2; }
msg_error() { echo "${RED}${BOLD}error${RESET} $*" >&2; }
msg_verbose() { [[ "${CTRL_VERBOSE}" == "1" ]] && echo "${DIM}[verbose]${RESET} $*" >&2 || true; }

fail() { msg_error "$*"; exit 1; }

require_cmd() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Required command not found: ${cmd}"
  done
}

has_cmd() { command -v "$1" >/dev/null 2>&1; }

# ── dry-run executor ──────────────────────────────────────────────────────────
# Usage: run_op "description" cmd arg1 arg2 ...
run_op() {
  local desc="$1"; shift
  if [[ "${CTRL_DRY_RUN}" == "1" ]]; then
    echo "${DIM}[DRY-RUN]${RESET} ${desc}: $*"
    return 0
  fi
  msg_verbose "exec: $*"
  "$@"
}

# ── config ────────────────────────────────────────────────────────────────────
CTRL_CONFIG_FILE="${CTRL_CONFIG:-}"
CTRL_META_PROJECT=""
CTRL_META_REGISTRY=""
CTRL_META_SSH_HOST=""
CTRL_META_SSH_USER="root"
CTRL_META_SSH_PORT="22"
CTRL_META_SSH_KEY=""
CTRL_META_COMPOSE_PATH="/opt/scaffold/docker-compose.yml"
CTRL_META_REMOTE_DIR="/opt/scaffold"

_find_config() {
  if [[ -n "${CTRL_CONFIG_FILE}" ]]; then
    [[ -f "${CTRL_CONFIG_FILE}" ]] || fail "Config file not found: ${CTRL_CONFIG_FILE}"
    return
  fi
  local dir="${PWD}"
  while [[ "${dir}" != "/" ]]; do
    if [[ -f "${dir}/ctrl.yaml" ]]; then
      CTRL_CONFIG_FILE="${dir}/ctrl.yaml"
      return
    fi
    dir="$(dirname "${dir}")"
  done
  fail "No ctrl.yaml found. Run 'ctrl init' or create one manually."
}

_require_yq() {
  require_cmd yq
}

# Resolve ${VAR} references in a string using current env
_resolve_env_refs() {
  echo "$1" | envsubst
}

load_config() {
  _find_config
  _require_yq
  msg_verbose "Loading config: ${CTRL_CONFIG_FILE}"

  # Load .local/ctrl.local.yaml overrides if present
  local local_cfg
  local_cfg="$(dirname "${CTRL_CONFIG_FILE}")/.local/ctrl.local.yaml"
  if [[ -f "${local_cfg}" ]]; then
    msg_verbose "Merging local overrides: ${local_cfg}"
    # yq merge: local overrides base (yq >=4 syntax)
    CTRL_YAML="$(yq '. *= load("'"${local_cfg}"'")' "${CTRL_CONFIG_FILE}")"
  else
    CTRL_YAML="$(cat "${CTRL_CONFIG_FILE}")"
  fi

  CTRL_META_PROJECT="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.project // ""')")"
  CTRL_META_REGISTRY="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.registry // ""')")"
  CTRL_META_SSH_HOST="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.ssh_host // ""')")"
  CTRL_META_SSH_USER="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.ssh_user // "root"')")"
  CTRL_META_SSH_PORT="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.ssh_port // "22"')")"
  CTRL_META_SSH_KEY="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.ssh_key // ""')")"
  CTRL_META_COMPOSE_PATH="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.compose_path // "/opt/scaffold/docker-compose.yml"')")"
  CTRL_META_REMOTE_DIR="$(dirname "${CTRL_META_COMPOSE_PATH}")"

  # Load env files listed in meta.env_files (optional)
  # Paths are relative to the ctrl.yaml directory
  local env_file ctrl_base
  ctrl_base="$(dirname "${CTRL_CONFIG_FILE}")"
  while IFS= read -r env_file; do
    [[ -z "${env_file}" || "${env_file}" == "null" ]] && continue
    env_file="$(_resolve_env_refs "${env_file}")"
    [[ "${env_file}" != /* ]] && env_file="${ctrl_base}/${env_file}"
    if [[ -f "${env_file}" ]]; then
      msg_verbose "Sourcing env file: ${env_file}"
      set -a; source "${env_file}"; set +a
    fi
  done < <(echo "${CTRL_YAML}" | yq '.meta.env_files[]? // ""')
}

# ── service accessors (read from CTRL_YAML) ───────────────────────────────────

ctrl_service_names() {
  echo "${CTRL_YAML}" | yq '.services[].name'
}

ctrl_service_field() {
  local svc="$1" field="$2"
  _resolve_env_refs "$(echo "${CTRL_YAML}" | yq ".services[] | select(.name == \"${svc}\") | ${field}")"
}

ctrl_service_exists() {
  local svc="$1"
  local found
  found="$(echo "${CTRL_YAML}" | yq ".services[] | select(.name == \"${svc}\") | .name" 2>/dev/null || true)"
  [[ -n "${found}" && "${found}" != "null" ]]
}

ctrl_resolve_services() {
  local -a out=()
  local token part normalized
  for token in "$@"; do
    IFS=',' read -r -a parts <<< "${token}"
    for part in "${parts[@]}"; do
      normalized="${part#"${part%%[![:space:]]*}"}"
      normalized="${normalized%"${normalized##*[![:space:]]}"}"
      normalized="$(tr '[:upper:]' '[:lower:]' <<< "${normalized}")"
      [[ -z "${normalized}" ]] && continue
      if [[ "${normalized}" == "all" ]]; then
        while IFS= read -r s; do out+=("${s}"); done < <(ctrl_service_names)
        echo "${out[@]}"; return
      fi
      ctrl_service_exists "${normalized}" || fail "Unknown service: ${normalized}"
      out+=("${normalized}")
    done
  done
  [[ "${#out[@]}" -gt 0 ]] || fail "No services resolved"
  echo "${out[@]}"
}

# ── SSH helpers ───────────────────────────────────────────────────────────────

_ssh_target() {
  [[ -n "${CTRL_META_SSH_HOST}" ]] || fail "meta.ssh_host is not set in ctrl.yaml"
  printf '%s@%s' "${CTRL_META_SSH_USER}" "${CTRL_META_SSH_HOST}"
}

_ssh_flags() {
  local flags=(-p "${CTRL_META_SSH_PORT}" -o StrictHostKeyChecking=accept-new)
  [[ -n "${CTRL_META_SSH_KEY}" ]] && flags+=(-i "${CTRL_META_SSH_KEY}")
  printf '%s\n' "${flags[@]}"
}

ctrl_ssh_run() {
  local command="$1"
  local target; target="$(_ssh_target)"
  local -a flags=()
  while IFS= read -r f; do flags+=("${f}"); done < <(_ssh_flags)
  if [[ -n "${SSH_PASSWORD:-}" ]] && has_cmd sshpass; then
    run_op "ssh ${target}" sshpass -p "${SSH_PASSWORD}" ssh "${flags[@]}" "${target}" "${command}"
  else
    run_op "ssh ${target}" ssh "${flags[@]}" "${target}" "${command}"
  fi
}

ctrl_scp_send() {
  local src="$1" dst="$2"
  local target; target="$(_ssh_target)"
  local -a flags=() # scp uses -P, but we build scp_flags below directly
  # rebuild properly
  local port="${CTRL_META_SSH_PORT}"
  local -a scp_flags=(-P "${port}" -o StrictHostKeyChecking=accept-new)
  [[ -n "${CTRL_META_SSH_KEY}" ]] && scp_flags+=(-i "${CTRL_META_SSH_KEY}")
  if [[ -n "${SSH_PASSWORD:-}" ]] && has_cmd sshpass; then
    run_op "scp ${src}" sshpass -p "${SSH_PASSWORD}" scp "${scp_flags[@]}" -r "${src}" "${target}:${dst}"
  else
    run_op "scp ${src}" scp "${scp_flags[@]}" -r "${src}" "${target}:${dst}"
  fi
}

# ── audit journal ─────────────────────────────────────────────────────────────

journal_entry() {
  local command="$1" services="$2" exit_code="$3" duration="$4"
  mkdir -p "${CTRL_JOURNAL_DIR}"
  printf '{"ts":"%s","version":"%s","project":"%s","command":"%s","services":"%s","host":"%s","operator":"%s","duration_s":%s,"exit_code":%s}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    "${CTRL_VERSION}" \
    "${CTRL_META_PROJECT}" \
    "${command}" \
    "${services}" \
    "${CTRL_META_SSH_HOST:-local}" \
    "${USER:-unknown}" \
    "${duration}" \
    "${exit_code}" \
    >> "${CTRL_JOURNAL}"
}

# Wrap a block and record it; usage: with_journal "cmd" "svc1 svc2" <function> [args]
with_journal() {
  local cmd="$1" svcs="$2"; shift 2
  local start; start="$(date +%s)"
  local exit_code=0
  "$@" || exit_code=$?
  local end; end="$(date +%s)"
  journal_entry "${cmd}" "${svcs}" "${exit_code}" "$((end - start))"
  return "${exit_code}"
}

# ════════════════════════════════════════════════════════════════════════════
# lib/services.sh
# ════════════════════════════════════════════════════════════════════════════
# services.sh — build (code + image), push, release

_svc_build_tool() { ctrl_service_field "$1" '.build.tool // "maven"'; }
_svc_build_dir()  { ctrl_service_field "$1" '.build.dir // ""'; }
_svc_build_args() { ctrl_service_field "$1" '.build.args // ""'; }
_svc_image()      { ctrl_service_field "$1" '.image // ""'; }
_svc_tag()        { ctrl_service_field "$1" '.tag // "latest"'; }
_svc_dockerfile() { ctrl_service_field "$1" '.build.dockerfile // "Dockerfile"'; }
_svc_context()    { ctrl_service_field "$1" '.build.context // ""'; }
_svc_platform()   { ctrl_service_field "$1" '.build.platform // "linux/amd64"'; }

_svc_image_ref() {
  local svc="$1"
  local image; image="$(_svc_image "${svc}")"
  local tag; tag="$(_svc_tag "${svc}")"
  [[ -n "${image}" ]] || fail "Service '${svc}' has no image defined in ctrl.yaml"
  printf '%s:%s' "${image}" "${tag}"
}

_svc_abs_dir() {
  local svc="$1"
  local dir; dir="$(_svc_build_dir "${svc}")"
  [[ -n "${dir}" ]] || fail "Service '${svc}' has no build.dir defined"
  # resolve relative to ctrl.yaml location
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"
  if [[ "${dir}" == /* ]]; then printf '%s' "${dir}"; else printf '%s/%s' "${base}" "${dir}"; fi
}

# ── sc-core / prerequisite builds ────────────────────────────────────────────
_SC_CORE_BUILT=0

_build_prerequisites() {
  local svc="$1"
  local prereqs; prereqs="$(echo "${CTRL_YAML}" | yq ".services[] | select(.name == \"${svc}\") | .build.prerequisites[]? // \"\"" 2>/dev/null || true)"
  [[ -z "${prereqs}" || "${prereqs}" == "null" ]] && return 0
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"
  local p
  while IFS= read -r p; do
    [[ -z "${p}" || "${p}" == "null" ]] && continue
    local abs_p="${base}/${p}"
    if [[ -f "${abs_p}/mvnw" ]]; then
      msg "Building prerequisite: ${p}"
      run_op "mvnw install ${p}" bash -c "cd '${abs_p}' && ./mvnw -Dmaven.test.skip=true clean install"
    elif [[ -f "${abs_p}/pom.xml" ]]; then
      msg "Building prerequisite: ${p}"
      run_op "mvn install ${p}" bash -c "cd '${abs_p}' && mvn -Dmaven.test.skip=true clean install"
    fi
  done <<< "${prereqs}"
}

# ── build code ────────────────────────────────────────────────────────────────
build_code_service() {
  local svc="$1"
  local tool; tool="$(_svc_build_tool "${svc}")"
  local dir; dir="$(_svc_abs_dir "${svc}")"
  local extra; extra="$(_svc_build_args "${svc}")"
  [[ -d "${dir}" ]] || fail "Build directory not found for '${svc}': ${dir}"

  _build_prerequisites "${svc}"

  case "${tool}" in
    maven)
      local wrapper="${dir}/mvnw"
      if [[ -f "${wrapper}" ]]; then
        run_op "build ${svc}" bash -c "cd '${dir}' && ./mvnw -Dmaven.test.skip=true clean package ${extra}"
      else
        run_op "build ${svc}" bash -c "cd '${dir}' && mvn -Dmaven.test.skip=true clean package ${extra}"
      fi
      ;;
    gradle)
      run_op "build ${svc}" bash -c "cd '${dir}' && ./gradlew build -x test ${extra}"
      ;;
    npm)
      run_op "build ${svc}" bash -c "cd '${dir}' && npm ci && npm run build ${extra}"
      ;;
    make)
      run_op "build ${svc}" bash -c "cd '${dir}' && make ${extra}"
      ;;
    shell)
      local script; script="$(ctrl_service_field "${svc}" '.build.script // ""')"
      [[ -n "${script}" ]] || fail "build.tool=shell requires build.script for service '${svc}'"
      run_op "build ${svc}" bash -c "cd '${dir}' && bash '${script}' ${extra}"
      ;;
    skip|none)
      msg_verbose "Skipping code build for ${svc} (tool=skip)"
      ;;
    *)
      fail "Unknown build.tool '${tool}' for service '${svc}'"
      ;;
  esac
  msg_ok "Built code: ${svc}"
}

# ── build image ───────────────────────────────────────────────────────────────
DOCKER_LOGGED_IN=0

_docker_login_once() {
  [[ "${DOCKER_LOGGED_IN}" -eq 0 ]] || return 0
  require_cmd docker
  local username="${DOCKERHUB_USERNAME:-}"
  local password="${DOCKERHUB_PASSWORD:-}"
  [[ -n "${username}" ]] || fail "DOCKERHUB_USERNAME is not set"
  [[ -n "${password}" ]] || fail "DOCKERHUB_PASSWORD is not set"
  msg "Logging into registry as ${username}"
  run_op "docker login" bash -c "printf '%s' '${password}' | docker login --username '${username}' --password-stdin"
  DOCKER_LOGGED_IN=1
}

build_image_service() {
  local svc="$1"
  local image_ref; image_ref="$(_svc_image_ref "${svc}")"
  local platform; platform="$(_svc_platform "${svc}")"

  local repo_dir; repo_dir="$(_svc_abs_dir "${svc}")"
  local dockerfile; dockerfile="$(_svc_dockerfile "${svc}")"
  local context; context="$(_svc_context "${svc}")"
  [[ -z "${context}" || "${context}" == "null" ]] && context="${repo_dir}"

  local df_path="${repo_dir}/${dockerfile}"
  [[ -f "${df_path}" ]] || fail "Dockerfile not found: ${df_path}"

  msg "Building image ${image_ref}"
  run_op "docker build ${svc}" docker buildx build \
    --platform "${platform}" \
    -f "${df_path}" \
    -t "${image_ref}" \
    --cache-from "type=registry,ref=${image_ref}-cache" \
    --cache-to   "type=registry,ref=${image_ref}-cache,mode=max" \
    "${context}"
  msg_ok "Built image: ${image_ref}"
}

push_image_service() {
  local svc="$1"
  local image_ref; image_ref="$(_svc_image_ref "${svc}")"
  _docker_login_once
  msg "Pushing ${image_ref}"
  run_op "docker push ${svc}" docker push "${image_ref}"
  msg_ok "Pushed: ${image_ref}"
}

release_service() {
  local svc="$1"
  build_code_service "${svc}"
  build_image_service "${svc}"
  push_image_service "${svc}"
}

# ════════════════════════════════════════════════════════════════════════════
# lib/deploy.sh
# ════════════════════════════════════════════════════════════════════════════
# deploy.sh — deployment target resolution, sync, deploy

# ── deployment target resolution ──────────────────────────────────────────────
# Reads deployments: from ctrl.yaml and sets CTRL_DEPLOY_* vars for the target.
# After calling resolve_deployment, CTRL_META_* SSH vars are overridden with
# the target's values so that ctrl_ssh_run / ctrl_scp_send use them.

CTRL_DEPLOY_NAME=""
CTRL_DEPLOY_SYNC_PATHS=()

resolve_deployment() {
  local target_name="${1:-}"

  # Find default name if not specified
  if [[ -z "${target_name}" ]]; then
    target_name="$(echo "${CTRL_YAML}" | yq '.deployments.default // ""')"
    [[ -n "${target_name}" && "${target_name}" != "null" ]] || \
      fail "No deployment target specified and no deployments.default set in ctrl.yaml"
  fi

  # Check the target exists
  local found; found="$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .name" 2>/dev/null || true)"
  [[ -n "${found}" && "${found}" != "null" ]] || \
    fail "Deployment target '${target_name}' not found in ctrl.yaml deployments.targets"

  CTRL_DEPLOY_NAME="${target_name}"

  # Override SSH meta with target-specific values (falls back to meta defaults)
  local t_ssh_host; t_ssh_host="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .ssh_host // \"\"")")"
  local t_ssh_user; t_ssh_user="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .ssh_user // \"\"")")"
  local t_ssh_port; t_ssh_port="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .ssh_port // \"\"")")"
  local t_ssh_key;  t_ssh_key="$(_resolve_env_refs  "$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .ssh_key // \"\"")")"
  local t_compose;  t_compose="$(_resolve_env_refs  "$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .compose_path // \"\"")")"

  [[ -n "${t_ssh_host}"  && "${t_ssh_host}"  != "null" ]] && CTRL_META_SSH_HOST="${t_ssh_host}"
  [[ -n "${t_ssh_user}"  && "${t_ssh_user}"  != "null" ]] && CTRL_META_SSH_USER="${t_ssh_user}"
  [[ -n "${t_ssh_port}"  && "${t_ssh_port}"  != "null" ]] && CTRL_META_SSH_PORT="${t_ssh_port}"
  [[ -n "${t_ssh_key}"   && "${t_ssh_key}"   != "null" ]] && CTRL_META_SSH_KEY="${t_ssh_key}"
  [[ -n "${t_compose}"   && "${t_compose}"   != "null" ]] && { CTRL_META_COMPOSE_PATH="${t_compose}"; CTRL_META_REMOTE_DIR="$(dirname "${t_compose}")"; }

  # Load sync paths for this target
  CTRL_DEPLOY_SYNC_PATHS=()
  while IFS= read -r p; do
    [[ -z "${p}" || "${p}" == "null" ]] && continue
    CTRL_DEPLOY_SYNC_PATHS+=("${p}")
  done < <(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${target_name}\") | .sync.paths[]? // \"\"")

  msg_verbose "Deployment target: ${CTRL_DEPLOY_NAME} → ${CTRL_META_SSH_USER}@${CTRL_META_SSH_HOST}:${CTRL_META_REMOTE_DIR}"
}

# Returns 0 if $1 is a known deployment target name, 1 otherwise
is_deployment_target() {
  local candidate="${1:-}"
  [[ -z "${candidate}" ]] && return 1
  local found; found="$(echo "${CTRL_YAML}" | yq ".deployments.targets[] | select(.name == \"${candidate}\") | .name" 2>/dev/null || true)"
  [[ -n "${found}" && "${found}" != "null" ]]
}

# ── service helpers ───────────────────────────────────────────────────────────

_svc_compose_service() {
  local svc="$1"
  local cs; cs="$(ctrl_service_field "${svc}" '.deploy.compose_service // ""')"
  [[ -n "${cs}" && "${cs}" != "null" ]] && printf '%s' "${cs}" || printf '%s' "${svc}"
}

_svc_compose_deps() {
  local svc="$1"
  echo "${CTRL_YAML}" | yq ".services[] | select(.name == \"${svc}\") | .deploy.depends_on[]? // \"\"" 2>/dev/null || true
}

_remote_export_block() {
  local svc
  local -a exports=()
  for svc in "$@"; do
    local img; img="$(ctrl_service_field "${svc}" '.image // ""')"
    local tag; tag="$(ctrl_service_field "${svc}" '.tag // "latest"')"
    [[ -z "${img}" || "${img}" == "null" ]] && continue
    local upper_name; upper_name="$(tr '[:lower:]-' '[:upper:]_' <<< "${svc}")"
    exports+=("export ${upper_name}_IMAGE=$(printf '%q' "${img}") ${upper_name}_TAG=$(printf '%q' "${tag}")")
  done
  [[ "${#exports[@]}" -gt 0 ]] && printf '%s; ' "${exports[@]}" || true
}

_remote_compose_services() {
  local svc
  local -a out=()
  for svc in "$@"; do out+=("$(_svc_compose_service "${svc}")"); done
  printf '%s ' "${out[@]}"
}

_remote_dep_services() {
  local svc dep
  local -a out=()
  for svc in "$@"; do
    while IFS= read -r dep; do
      [[ -z "${dep}" || "${dep}" == "null" ]] && continue
      out+=("${dep}")
    done < <(_svc_compose_deps "${svc}")
  done
  [[ "${#out[@]}" -gt 0 ]] && printf '%s ' "${out[@]}" || true
}

# ── deploy ────────────────────────────────────────────────────────────────────

deploy_services() {
  local -a svcs=("$@")
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  local exports; exports="$(_remote_export_block "${svcs[@]}")"; exports="${exports%'; '}"
  local compose_svcs; compose_svcs="$(_remote_compose_services "${svcs[@]}" | sed 's/ $//')"
  local dep_svcs; dep_svcs="$(_remote_dep_services "${svcs[@]}" | sed 's/ $//')"

  [[ -n "${compose_svcs// }" ]] || fail "No compose services resolved for: ${svcs[*]}"

  local cmd="cd $(printf '%q' "${remote_dir}")"
  [[ -n "${exports}" ]] && cmd+=" && ${exports}"
  [[ -n "${dep_svcs// }" ]] && cmd+=" && docker compose up -d ${dep_svcs}"
  cmd+=" && docker compose pull ${compose_svcs} && docker compose up -d --no-deps --force-recreate ${compose_svcs}"

  msg "[$CTRL_DEPLOY_NAME] Deploying: ${compose_svcs}"
  ctrl_ssh_run "${cmd}"
  msg_ok "[$CTRL_DEPLOY_NAME] Deploy finished"
}

# ── sync ──────────────────────────────────────────────────────────────────────

sync_files() {
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"

  if [[ "${#CTRL_DEPLOY_SYNC_PATHS[@]}" -eq 0 ]]; then
    msg_warn "[$CTRL_DEPLOY_NAME] No sync.paths defined for this target; nothing to sync"
    return 0
  fi

  msg "[$CTRL_DEPLOY_NAME] Syncing → ${CTRL_META_SSH_HOST}:${remote_dir}"
  ctrl_ssh_run "mkdir -p $(printf '%q' "${remote_dir}")"
  local p abs_p
  for p in "${CTRL_DEPLOY_SYNC_PATHS[@]}"; do
    abs_p="${base}/${p}"
    [[ -e "${abs_p}" ]] || { msg_warn "Sync path not found, skipping: ${abs_p}"; continue; }
    ctrl_scp_send "${abs_p}" "${remote_dir}/"
  done
  msg_ok "[$CTRL_DEPLOY_NAME] Sync complete"
}

# ════════════════════════════════════════════════════════════════════════════
# lib/remote.sh
# ════════════════════════════════════════════════════════════════════════════
# remote.sh — ssh, remote-status, remote-logs, inspect

open_ssh() {
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  local target; target="${CTRL_META_SSH_USER}@${CTRL_META_SSH_HOST}"
  local port="${CTRL_META_SSH_PORT}"
  local cmd="cd $(printf '%q' "${remote_dir}") && exec \${SHELL:-bash} -l"

  local -a flags=(-t -p "${port}" -o StrictHostKeyChecking=accept-new)
  [[ -n "${CTRL_META_SSH_KEY}" ]] && flags+=(-i "${CTRL_META_SSH_KEY}")

  if [[ -n "${SSH_PASSWORD:-}" ]] && has_cmd sshpass; then
    sshpass -p "${SSH_PASSWORD}" ssh "${flags[@]}" "${target}" "${cmd}"
  else
    ssh "${flags[@]}" "${target}" "${cmd}"
  fi
}

remote_status() {
  local svc="${1:-}"
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  if [[ -n "${svc}" ]]; then
    local cs; cs="$(_svc_compose_service "${svc}")"
    ctrl_ssh_run "cd $(printf '%q' "${remote_dir}") && docker compose ps ${cs}"
  else
    ctrl_ssh_run "cd $(printf '%q' "${remote_dir}") && docker compose ps"
  fi
}

remote_logs() {
  local svc="$1"
  local lines="${2:-200}"
  local follow="${CTRL_FOLLOW:-0}"
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  ctrl_service_exists "${svc}" || fail "Unknown service: ${svc}"
  local cs; cs="$(_svc_compose_service "${svc}")"
  local tail_flag="--tail ${lines}"
  local follow_flag=""
  [[ "${follow}" == "1" ]] && follow_flag="--follow"
  ctrl_ssh_run "cd $(printf '%q' "${remote_dir}") && docker compose logs ${tail_flag} ${follow_flag} ${cs}"
}

remote_inspect() {
  local svc="$1"
  ctrl_service_exists "${svc}" || fail "Unknown service: ${svc}"
  local cs; cs="$(_svc_compose_service "${svc}")"
  local remote_dir="${CTRL_META_REMOTE_DIR}"
  ctrl_ssh_run "cd $(printf '%q' "${remote_dir}") && docker compose exec ${cs} env | sort"
}

# ════════════════════════════════════════════════════════════════════════════
# lib/health.sh
# ════════════════════════════════════════════════════════════════════════════
# health.sh — health-check, wait-ready, smoke-test

_svc_health_url() {
  local svc="$1"
  local url; url="$(ctrl_service_field "${svc}" '.health.url // ""')"
  [[ -n "${url}" && "${url}" != "null" ]] && printf '%s' "${url}" && return
  # derive from meta.registry host or local defaults
  local port; port="$(ctrl_service_field "${svc}" '.health.port // ""')"
  [[ -n "${port}" && "${port}" != "null" ]] && printf 'http://localhost:%s/actuator/health' "${port}" && return
  printf ''
}

health_check_service() {
  local svc="$1"
  ctrl_service_exists "${svc}" || fail "Unknown service: ${svc}"
  local url; url="$(_svc_health_url "${svc}")"
  [[ -n "${url}" ]] || { msg_warn "No health.url or health.port for ${svc} — skipping"; return 0; }
  require_cmd curl

  # If a deployment target is active, run the curl on the remote VM
  if [[ -n "${CTRL_META_SSH_HOST:-}" ]]; then
    msg "Health check: ${svc} → ${url} (via ${CTRL_META_SSH_HOST})"
    local http_code
    http_code="$(ctrl_ssh_run "curl -s -o /dev/null -w '%{http_code}' --max-time 5 '${url}'" || echo "000")"
    http_code="${http_code//[[:space:]]/}"
  else
    msg "Health check: ${svc} → ${url}"
    local http_code
    http_code="$(run_op "curl ${url}" curl -s -o /dev/null -w '%{http_code}' --max-time 5 "${url}" || echo "000")"
  fi

  if [[ "${http_code}" == "200" ]]; then
    msg_ok "${svc} is healthy (HTTP ${http_code})"
  else
    msg_error "${svc} returned HTTP ${http_code} at ${url}"
    return 1
  fi
}

wait_ready_service() {
  local svc="$1"
  local timeout="${2:-60}"
  ctrl_service_exists "${svc}" || fail "Unknown service: ${svc}"
  local url; url="$(_svc_health_url "${svc}")"
  [[ -n "${url}" ]] || { msg_warn "No health.url or health.port for ${svc} — skipping"; return 0; }
  require_cmd curl
  msg "Waiting for ${svc} to be ready (timeout: ${timeout}s)"
  local elapsed=0
  while [[ "${elapsed}" -lt "${timeout}" ]]; do
    local http_code
    http_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "${url}" 2>/dev/null || echo "000")"
    if [[ "${http_code}" == "200" ]]; then
      msg_ok "${svc} is ready"
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done
  fail "${svc} did not become ready within ${timeout}s"
}

smoke_test_services() {
  local -a svcs=("$@")
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"
  local svc script_name script_path
  local found=0

  for svc in "${svcs[@]}"; do
    while IFS= read -r script_name; do
      [[ -z "${script_name}" || "${script_name}" == "null" ]] && continue
      found=1
      # find the script in the scripts list
      script_path="$(echo "${CTRL_YAML}" | yq ".scripts[] | select(.name == \"${script_name}\") | .path // \"\"" || true)"
      [[ -n "${script_path}" && "${script_path}" != "null" ]] || fail "Smoke test script '${script_name}' not found in scripts:"
      local abs="${base}/${script_path}"
      [[ -f "${abs}" ]] || fail "Script file not found: ${abs}"
      msg "Smoke test [${svc}]: ${script_name}"
      run_op "smoke ${script_name}" bash "${abs}"
    done < <(echo "${CTRL_YAML}" | yq ".services[] | select(.name == \"${svc}\") | .smoke_tests[]? // \"\"")
  done

  [[ "${found}" -eq 1 ]] || msg_warn "No smoke tests defined for: ${svcs[*]}"
}

# ════════════════════════════════════════════════════════════════════════════
# lib/audit.sh
# ════════════════════════════════════════════════════════════════════════════
# audit.sh — history display, journal helpers (journal_entry is in core.sh)

show_history() {
  local lines="${1:-20}"
  [[ -f "${CTRL_JOURNAL}" ]] || { msg_warn "No journal found at ${CTRL_JOURNAL}"; return 0; }
  require_cmd jq
  tail -n "${lines}" "${CTRL_JOURNAL}" | jq -r \
    '"\(.ts)  \(.command | @sh)  svcs=\(.services)  exit=\(.exit_code)  \(.duration_s)s"'
}

# ════════════════════════════════════════════════════════════════════════════
# lib/ext.sh
# ════════════════════════════════════════════════════════════════════════════
# ext.sh — named script runner and plugin (extension) loader

run_script() {
  local name="$1"; shift
  local extra_args=("$@")
  while [[ "${#extra_args[@]}" -gt 0 && "${extra_args[0]}" == "--" ]]; do
    extra_args=("${extra_args[@]:1}")
  done
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"

  local path
  path="$(echo "${CTRL_YAML}" | yq ".scripts[] | select(.name == \"${name}\") | .path // \"\"" 2>/dev/null || true)"
  [[ -n "${path}" && "${path}" != "null" ]] || fail "Script '${name}' not found in ctrl.yaml scripts:"

  local abs="${base}/${path}"
  [[ -f "${abs}" ]] || fail "Script file not found: ${abs}"

  export CTRL_PROJECT="${CTRL_META_PROJECT}"
  export CTRL_SSH_HOST="${CTRL_META_SSH_HOST}"
  export CTRL_REGISTRY="${CTRL_META_REGISTRY}"
  export CTRL_REMOTE_DIR="${CTRL_META_REMOTE_DIR}"
  export CTRL_CONFIG_FILE
  export F33D_URL; F33D_URL="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.f33d.url // ""')")"
  export F33D_TOKEN; F33D_TOKEN="$(_resolve_env_refs "$(echo "${CTRL_YAML}" | yq '.meta.f33d.token // ""')")"

  local hook
  while IFS= read -r hook; do
    [[ -z "${hook}" || "${hook}" == "null" ]] && continue
    run_script "${hook}"
  done < <(echo "${CTRL_YAML}" | yq ".scripts[] | select(.name == \"${name}\") | .hooks.pre[]? // \"\"")

  msg "Running script: ${name}"
  local exit_code=0
  run_op "script ${name}" bash "${abs}" "${extra_args[@]+"${extra_args[@]}"}" || exit_code=$?

  export CTRL_EXIT_CODE="${exit_code}"
  if [[ "${exit_code}" -ne 0 ]]; then export F33D_LEVEL="error"; else export F33D_LEVEL="success"; fi
  if [[ "${exit_code}" -ne 0 ]]; then export F33D_MESSAGE="ctrl ${name}: failed"; else export F33D_MESSAGE="ctrl ${name}: done"; fi
  while IFS= read -r hook; do
    [[ -z "${hook}" || "${hook}" == "null" ]] && continue
    run_script "${hook}" || true
  done < <(echo "${CTRL_YAML}" | yq ".scripts[] | select(.name == \"${name}\") | .hooks.post[]? // \"\"")

  [[ "${exit_code}" -eq 0 ]] || return "${exit_code}"
  msg_ok "Script finished: ${name}"
}

list_scripts() {
  echo "${CTRL_YAML}" | yq '.scripts[] | "\(.name)\t\(.description // "")"' | \
    while IFS=$'\t' read -r name desc; do
      printf '  %-24s %s\n' "${name}" "${desc}"
    done
}

load_extensions() {
  local base; base="$(dirname "${CTRL_CONFIG_FILE}")"
  local p abs
  while IFS= read -r p; do
    [[ -z "${p}" || "${p}" == "null" ]] && continue
    abs="${base}/${p}"
    if [[ -f "${abs}" ]]; then
      msg_verbose "Loading extension: ${abs}"
      # shellcheck disable=SC1090
      source "${abs}"
    else
      msg_warn "Extension not found, skipping: ${abs}"
    fi
  done < <(echo "${CTRL_YAML}" | yq '.extensions[]? // ""')
}

# ════════════════════════════════════════════════════════════════════════════
# ctrl.sh — entry point
# ════════════════════════════════════════════════════════════════════════════




# ── helpers ───────────────────────────────────────────────────────────────────
run_for_each() {
  local action="$1"; shift
  for svc in "$@"; do "${action}" "${svc}"; done
}

run_for_each_continue() {
  local action="$1"; shift
  local failed=0
  for svc in "$@"; do "${action}" "${svc}" || failed=1; done
  return "${failed}"
}

# Resolve optional deployment target from first arg.
# If $1 is a known deployment name, sets it and shifts CTRL_ARGS.
# Otherwise uses the default target. Remaining CTRL_ARGS are service selectors.
_resolve_target_and_services() {
  local -a args=("$@")
  if [[ "${#args[@]}" -gt 0 ]] && is_deployment_target "${args[0]}"; then
    resolve_deployment "${args[0]}"
    args=("${args[@]:1}")
  else
    resolve_deployment ""
  fi
  # Return remaining args as services (caller reads CTRL_SVC_ARGS)
  CTRL_SVC_ARGS=("${args[@]+"${args[@]}"}")
}

# ── global flag parsing ───────────────────────────────────────────────────────
CTRL_FOLLOW=0
_parse_global_flags() {
  local -a remaining=()
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --dry-run)    CTRL_DRY_RUN=1 ;;
      --verbose|-v) CTRL_VERBOSE=1 ;;
      --config)     shift; CTRL_CONFIG_FILE="$1" ;;
      --follow)     CTRL_FOLLOW=1 ;;
      *)            remaining+=("$1") ;;
    esac
    shift
  done
  CTRL_ARGS=("${remaining[@]+"${remaining[@]}"}")
}

_parse_global_flags "$@"
set -- "${CTRL_ARGS[@]+"${CTRL_ARGS[@]}"}"

# ── version / help (no config needed) ────────────────────────────────────────
case "${1:-}" in
  version|--version|-V)
    echo "ctrl v${CTRL_VERSION}"
    exit 0
    ;;
  help|--help|-h|"")
    cat <<EOF
ctrl v${CTRL_VERSION} — YAML-driven platform operations CLI

Usage: ctrl [--dry-run] [--verbose] [--config <path>] <command> [args]

Service commands:
  list  / ls                        List services defined in ctrl.yaml
  build / b    <svc|all>            Build service code locally
  image / i    <svc|all>            Build Docker image (no push)
  push  / pu   <svc|all>            Push image to registry
  rel          <svc|all>            build + image + push
  dep          [target] [svc|all]   Pull and start on deployment target (default: deployments.default)
  rdep         [target] [svc|all]   rel + dep

Deployment commands:
  sync         [target]             Sync files to deployment target
  dep          [target] [svc|all]   Pull + start services on target
  rdep         [target] [svc|all]   rel + dep on target

Remote commands:
  ssh / sr     [target] [cmd]        Interactive SSH or run a remote command
  rs           [svc]                Remote status (docker compose ps)
  rl           <svc> [lines]        Remote logs (--follow to tail)
  insp         <svc>                Show env of running container

Health commands:
  hc           [svc|all]            Health check
  wr           <svc> [timeout]      Wait until healthy
  st           [svc|all]            Smoke test

Script commands:
  run          <name> [args]        Run a named script
  scripts      / sc                 List scripts

Audit:
  hist         [n]                  Last n journal entries (default 20)
  plan                              Dry-run mode (alias for --dry-run)
  version                           Print ctrl version

Global flags:
  --dry-run    -n                   Print commands, no execution
  --verbose    -v                   Extra debug output
  --config     <path>               Override ctrl.yaml location
  --follow                          Tail logs (with rl)

Deployment targets are defined under deployments: in ctrl.yaml.
When [target] is omitted, deployments.default is used.

EOF
    exit 0
    ;;
esac

# ── commands that need config ─────────────────────────────────────────────────
load_config
load_extensions

CMD="${1:-}"; shift || true
CTRL_SVC_ARGS=()

case "${CMD}" in

  # ── GitLab project info ───────────────────────────────────────────────
  gitlab-project-info)
    [[ "$#" -ge 1 ]] || fail "Usage: ctrl gitlab-project-info <project-id-or-path>"
    ctrl_gitlab_project_info "$1"
    ;;

  # ── GitLab runner deploy ──────────────────────────────────────────────
  gitlab-runner-deploy)
    ctrl_gitlab_runner_deploy
    ;;

  # ── list ──────────────────────────────────────────────────────────────────
  list|ls)
    printf '%s%-20s %-40s %s%s\n' "${BOLD}" "SERVICE" "DESCRIPTION" "IMAGE:TAG" "${RESET}"
    while IFS= read -r svc; do
      svc_img="$(ctrl_service_field "${svc}" '.image // "-"'):$(ctrl_service_field "${svc}" '.tag // "latest"')"
      svc_desc="$(ctrl_service_field "${svc}" '.description // ""')"
      printf '  %-20s %-40s %s\n' "${svc}" "${svc_desc}" "${svc_img}"
    done < <(ctrl_service_names)
    ;;

  # ── build ─────────────────────────────────────────────────────────────────
  build|b)
    [[ "$#" -gt 0 ]] || fail "Usage: ctrl b <svc|all>"
    read -r -a svcs <<< "$(ctrl_resolve_services "$@")"
    with_journal "build" "${svcs[*]}" run_for_each build_code_service "${svcs[@]}"
    ;;

  # ── image ─────────────────────────────────────────────────────────────────
  image|i)
    [[ "$#" -gt 0 ]] || fail "Usage: ctrl i <svc|all>"
    read -r -a svcs <<< "$(ctrl_resolve_services "$@")"
    with_journal "image" "${svcs[*]}" run_for_each build_image_service "${svcs[@]}"
    ;;

  # ── push ──────────────────────────────────────────────────────────────────
  push|pu)
    [[ "$#" -gt 0 ]] || fail "Usage: ctrl pu <svc|all>"
    read -r -a svcs <<< "$(ctrl_resolve_services "$@")"
    with_journal "push" "${svcs[*]}" run_for_each push_image_service "${svcs[@]}"
    ;;

  # ── release ───────────────────────────────────────────────────────────────
  release|rel)
    [[ "$#" -gt 0 ]] || fail "Usage: ctrl rel <svc|all>"
    read -r -a svcs <<< "$(ctrl_resolve_services "$@")"
    with_journal "release" "${svcs[*]}" run_for_each release_service "${svcs[@]}"
    ;;

  # ── sync ──────────────────────────────────────────────────────────────────
  sync)
    _resolve_target_and_services "$@"
    with_journal "sync" "${CTRL_DEPLOY_NAME}" sync_files
    ;;

  # ── deploy ────────────────────────────────────────────────────────────────
  deploy|dep)
    _resolve_target_and_services "$@"
    if [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 ]]; then
      read -r -a svcs <<< "$(ctrl_resolve_services "${CTRL_SVC_ARGS[@]}")"
    else
      read -r -a svcs <<< "$(ctrl_resolve_services all)"
    fi
    with_journal "deploy" "${CTRL_DEPLOY_NAME}:${svcs[*]}" deploy_services "${svcs[@]}"
    ;;

  # ── redeploy ──────────────────────────────────────────────────────────────
  redeploy|rdep)
    _resolve_target_and_services "$@"
    if [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 ]]; then
      read -r -a svcs <<< "$(ctrl_resolve_services "${CTRL_SVC_ARGS[@]}")"
    else
      read -r -a svcs <<< "$(ctrl_resolve_services all)"
    fi
    run_for_each release_service "${svcs[@]}"
    with_journal "redeploy" "${CTRL_DEPLOY_NAME}:${svcs[*]}" deploy_services "${svcs[@]}"
    ;;

  # ── sync + deploy ─────────────────────────────────────────────────────────
  sync-deploy|sdep)
    _resolve_target_and_services "$@"
    if [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 ]]; then
      read -r -a svcs <<< "$(ctrl_resolve_services "${CTRL_SVC_ARGS[@]}")"
    else
      read -r -a svcs <<< "$(ctrl_resolve_services all)"
    fi
    sync_files
    with_journal "sync-deploy" "${CTRL_DEPLOY_NAME}:${svcs[*]}" deploy_services "${svcs[@]}"
    ;;

  # ── ssh / sr ──────────────────────────────────────────────────────────────
  ssh|sr)
    _resolve_target_and_services "$@"
    # strip leading '--' option-separator that users sometimes include
    while [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 && "${CTRL_SVC_ARGS[0]}" == "--" ]]; do
      CTRL_SVC_ARGS=("${CTRL_SVC_ARGS[@]:1}")
    done
    if [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 ]]; then
      ctrl_ssh_run "${CTRL_SVC_ARGS[*]}"
    else
      open_ssh
    fi
    ;;

  # ── remote-status ─────────────────────────────────────────────────────────
  remote-status|rs)
    _resolve_target_and_services "$@"
    remote_status "${CTRL_SVC_ARGS[0]:-}"
    ;;

  # ── remote-logs ───────────────────────────────────────────────────────────
  remote-logs|rl)
    _resolve_target_and_services "$@"
    [[ "${#CTRL_SVC_ARGS[@]}" -ge 1 ]] || fail "Usage: ctrl rl [target] <svc> [lines]"
    remote_logs "${CTRL_SVC_ARGS[0]}" "${CTRL_SVC_ARGS[1]:-200}"
    ;;

  # ── inspect ───────────────────────────────────────────────────────────────
  inspect|insp)
    _resolve_target_and_services "$@"
    [[ "${#CTRL_SVC_ARGS[@]}" -ge 1 ]] || fail "Usage: ctrl insp [target] <svc>"
    remote_inspect "${CTRL_SVC_ARGS[0]}"
    ;;

  # ── health-check ──────────────────────────────────────────────────────────
  health-check|hc)
    _resolve_target_and_services "$@"
    svcs=()
    if [[ "${#CTRL_SVC_ARGS[@]}" -gt 0 ]]; then
      read -r -a svcs <<< "$(ctrl_resolve_services "${CTRL_SVC_ARGS[@]}")"
    else
      read -r -a svcs <<< "$(ctrl_resolve_services all)"
    fi
    run_for_each_continue health_check_service "${svcs[@]}"
    ;;

  # ── wait-ready ────────────────────────────────────────────────────────────
  wait-ready|wr)
    [[ "$#" -ge 1 ]] || fail "Usage: ctrl wr <svc> [timeout]"
    wait_ready_service "$1" "${2:-60}"
    ;;

  # ── smoke-test ────────────────────────────────────────────────────────────
  smoke-test|st)
    if [[ "$#" -gt 0 ]]; then
      read -r -a svcs <<< "$(ctrl_resolve_services "$@")"
    else
      read -r -a svcs <<< "$(ctrl_resolve_services all)"
    fi
    smoke_test_services "${svcs[@]}"
    ;;

  # ── run script ────────────────────────────────────────────────────────────
  run)
    [[ "$#" -ge 1 ]] || fail "Usage: ctrl run <name> [args]"
    _script_name="$1"; shift
    run_script "${_script_name}" "$@"
    ;;

  # ── list scripts ──────────────────────────────────────────────────────────
  scripts|sc)
    printf '%s%-24s %s%s\n' "${BOLD}" "SCRIPT" "DESCRIPTION" "${RESET}"
    list_scripts
    ;;

  # ── history ───────────────────────────────────────────────────────────────
  history|hist)
    show_history "${1:-20}"
    ;;

  # ── plan / dry-run ────────────────────────────────────────────────────────
  plan)
    CTRL_DRY_RUN=1
    msg "Dry-run mode — no changes will be made. Use --dry-run on any command for the same effect."
    ;;

  version)
    echo "ctrl v${CTRL_VERSION}"
    ;;

  # ── extension commands ────────────────────────────────────────────────────
  *)
    _ext_fn="ctrl_cmd_${CMD//-/_}"
    if declare -f "${_ext_fn}" >/dev/null 2>&1; then
      "${_ext_fn}" "$@"
    else
      fail "Unknown command: ${CMD}. Run 'ctrl help' for usage."
    fi
    ;;
esac
